# Generated by Django 5.1.6 on 2025-11-04 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixel_app', '0004_remove_lightinglog_lighting_action_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lightinglog',
            name='lighting_action_class',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='lightinglog',
            name='motion_detected',
            field=models.IntegerField(),
        ),
    ]
