# Generated by Django 5.1.6 on 2025-11-08 04:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixel_app', '0005_alter_lightinglog_lighting_action_class_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lightinglog',
            name='source',
            field=models.CharField(default='iot', max_length=20),
        ),
        migrations.AlterField(
            model_name='lightinglog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
