# Generated by Django 5.2.8 on 2025-12-06 05:18

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixel_app', '0006_lightinglog_source_alter_lightinglog_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lightinglog',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Lighting Log', 'verbose_name_plural': 'Lighting Logs'},
        ),
        migrations.AddField(
            model_name='lightinglog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lightinglog',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lightinglog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='lightinglog',
            name='day_of_week',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lightinglog',
            name='lighting_action_class',
            field=models.IntegerField(choices=[(0, 'OFF'), (1, 'ON')], default=0),
        ),
        migrations.AlterField(
            model_name='lightinglog',
            name='motion_detected',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lightinglog',
            name='source',
            field=models.CharField(choices=[('iot', 'IoT Sensor'), ('web', 'Web Dashboard'), ('manual', 'Manual Control'), ('api', 'API')], default='iot', max_length=20),
        ),
        migrations.AlterField(
            model_name='lightinglog',
            name='time_of_day',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lightinglog',
            name='weather_condition',
            field=models.IntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='lightinglog',
            index=models.Index(fields=['-timestamp'], name='pixel_app_l_timesta_f3744f_idx'),
        ),
        migrations.AddIndex(
            model_name='lightinglog',
            index=models.Index(fields=['user', '-timestamp'], name='pixel_app_l_user_id_f4c66b_idx'),
        ),
        migrations.AddIndex(
            model_name='lightinglog',
            index=models.Index(fields=['lighting_action_class'], name='pixel_app_l_lightin_5bf229_idx'),
        ),
        migrations.AddIndex(
            model_name='lightinglog',
            index=models.Index(fields=['source'], name='pixel_app_l_source_c66c17_idx'),
        ),
    ]
