# Generated by Django 5.2.8 on 2025-12-06 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixel_app', '0007_alter_lightinglog_options_lightinglog_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lightinglog',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='lightinglog',
            name='pixel_app_l_timesta_f3744f_idx',
        ),
        migrations.RemoveIndex(
            model_name='lightinglog',
            name='pixel_app_l_user_id_f4c66b_idx',
        ),
        migrations.RemoveIndex(
            model_name='lightinglog',
            name='pixel_app_l_lightin_5bf229_idx',
        ),
        migrations.RemoveIndex(
            model_name='lightinglog',
            name='pixel_app_l_source_c66c17_idx',
        ),
        migrations.RemoveField(
            model_name='lightinglog',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='lightinglog',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='lightinglog',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='lightinglog',
            name='day_of_week',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='lightinglog',
            name='lighting_action_class',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='lightinglog',
            name='motion_detected',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='lightinglog',
            name='source',
            field=models.CharField(default='iot', max_length=20),
        ),
        migrations.AlterField(
            model_name='lightinglog',
            name='time_of_day',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='lightinglog',
            name='weather_condition',
            field=models.IntegerField(),
        ),
    ]
