# Generated by Django 5.2.8 on 2025-12-06 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixel_app', '0008_alter_lightinglog_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LightState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('AUTO', 'AUTO'), ('MANUAL', 'MANUAL')], default='AUTO', max_length=10)),
                ('status', models.CharField(choices=[('ON', 'ON'), ('OFF', 'OFF')], default='OFF', max_length=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
