# Generated by Django 5.1.6 on 2025-10-28 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixel_app', '0002_lightinglog_delete_lightstatus_delete_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='lightinglog',
            name='day_of_week',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lightinglog',
            name='time_of_day',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lightinglog',
            name='motion_detected',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lightinglog',
            name='weather_condition',
            field=models.IntegerField(),
        ),
    ]
