# Generated by Django 5.1.6 on 2025-11-04 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixel_app', '0003_lightinglog_day_of_week_lightinglog_time_of_day_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lightinglog',
            name='lighting_action',
        ),
        migrations.AddField(
            model_name='lightinglog',
            name='lighting_action_class',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lightinglog',
            name='motion_detected',
            field=models.IntegerField(default=0),
        ),
    ]
