# Generated by Django 5.2.8 on 2025-12-06 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixel_app', '0009_lightstate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lightinglog',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='lightstate',
            options={'verbose_name': 'Light State', 'verbose_name_plural': 'Light States'},
        ),
        migrations.AddField(
            model_name='lightinglog',
            name='control_mode',
            field=models.CharField(choices=[('AUTO', 'Auto'), ('MANUAL', 'Manual')], default='AUTO', max_length=10),
        ),
        migrations.AddField(
            model_name='lightinglog',
            name='is_manual',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lightinglog',
            name='manual_command',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
